### ISSUE TITLE
Formatting Problems and consequent bugs

### ISSUE THREAD

**Issue by SyncBS** [rithik-b/LeaderboardCore#11]
When a player only has BeatLeader the Leaderboard names will be pushed up and clip through the top banner, asked in BL and I was told it was a LBC issue, here's what I found though.

The Problem in case:
![Beat_Saber_xL3939VvEY](https://user-images.githubusercontent.com/86927709/227734844-ef15dc74-d1a1-4fb4-9096-db468881b6c9.png)

You can make it go to normal if you first open a vanilla leaderboard and then go into custom songs again,

https://user-images.githubusercontent.com/86927709/227735167-47811d03-789e-48ef-be94-9808629d2940.mp4

Except this causes an issue, the arrow for other Leaderboards (hitbloq in this case) stops showing up and you cannot access it unless you restart or soft restart.
![Beat_Saber_Q296u5yFf1](https://user-images.githubusercontent.com/86927709/227735215-ce120fb1-44f3-4493-a247-7016773f7af9.jpg)

**Comment by Sirspam** [comment]
Fixed in commit 6b18c2b218bc5b45c71928e197bec84bcae7de18
